# Permalinks
permalink:            pretty

# reveal options
reveal:
  slide_separator:    "<hr />"
  vertical_separator: "<p>~~</p>"
  notes_separator:    "<p>Notes:</p>"
  title_slide:        true
  cdn:               "https://cdn.bootcss.com/reveal.js/3.5.0/"

# Setup
title:                Slides of New Future
tagline:              "Markdown slides in Jekyll using reveal.js"
description:          "Slides of New Future"
url:                  http://slides.newfuture.cc

markdown:             kramdown
kramdown:
  input:              GFM

collections:
  slides:
    output:           true
    permalink:        /:title/

# About/contact
author:
  name:               NewFuture
  url:                https://github.com/NewFuture
  email:              github@newfuture.cc

# YAML defaults
defaults:
  - scope:
      path: ""
      type: slides
    values:
      layout: slides

# Compress html 压缩HTML
compress_html:
  #去除空格
  clippings: [html, head, title, base, link, meta, style, script, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th, i,
   svg, summary, details, '!--[if lte IE 9]','![endif]--']
  #去除注释
  comments: all

#css 合并压缩css
sass:
  style: compressed
  sass_dir: _sass