# Permalinks
permalink:            pretty

# reveal options
reveal:
  slide_separator:    "<hr />"
  vertical_separator: "<p>~~</p>"
  notes_separator:    "<p>Notes:</p>"
  title_slide:        true
  cdn:               "https://cdn.bootcss.com/reveal.js/3.5.0/"

# Setup
title:                Slides of New Future
tagline:              "Markdown slides in Jekyll using reveal.js"
description:          "Slides of New Future"
url:                  https://newfuture.github.io/slides

markdown:             kramdown
kramdown:
  input:              GFM

collections:
  slides:
    output:           true
    permalink:        /:title/

# About/contact
author:
  name:               NewFuture
  url:                https://github.com/NewFuture
  email:              github@newfuture.cc

# YAML defaults
defaults:
  - scope:
      path: ""
      type: slides
    values:
      layout: slides
