# Setup
title:                "Future Slides"
tagline:              "未来的幻灯片集"
description:          "Slide decks New Future wrote"
url:                  "https://slides.newfuture.cc"

# reveal options
reveal:
  theme: "night"
  slide_separator:    ""
  slide_separator:    "<hr />"
  vertical_separator: "<p>~~</p>"
  notes_separator:    "<p>Notes:</p>"
  title_slide:        true
  # cdn:               "https://cdn.bootcss.com/reveal.js/3.5.0/"
  cdn:               "/assets/"
  # qrcode:            "http://qr.topscan.com/api.php?w=200&m=10&logo=http://slides.newfuture.cc/assets/icon/avatar.min.jpg&text="  
  # qrcode:            "https://pan.baidu.com/share/qrcode?w=200&h=200&url="
  qrcode:             "https://api.qrserver.com/v1/create-qr-code/?size=100x100&format=svg&data="

github:
  url: https://github.com/NewFuture/slides
  branch: gh-pages
  
markdown:             kramdown
kramdown:
  input:              GFM

collections:
  slides:
    output:           true
    permalink:        /:title/

# About/contact
author:
  name:               NewFuture
  url:                https://github.com/NewFuture
  email:              github@newfuture.cc

# YAML defaults
defaults:
  - scope:
      path: ""
      type: slides
    values:
      layout: slides

# Compress html 压缩HTML
compress_html:
  #去除空格
  clippings: [html, head, title, base, link, meta, style, script, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th, i,
   svg, summary, details, '!--[if lte IE 9]','![endif]--']
  #去除注释
  comments: all

#css 合并压缩css
sass:
  style: compressed
  sass_dir: _sass

#插件
gems:
  - jekyll-redirect-from
